3.1.0 caf runtime, scripts, and regression test changes
For more details, please see the openuh commit logs.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -271,7 +271,7 @@ PACKAGE_VERSION='4.2'
 PACKAGE_STRING='opencc 4.2'
 PACKAGE_BUGREPORT=''
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os BASH_PATH MPICC_PATH MACHINE_TYPE BUILD_ABI BUILD_ARCH BUILD_HOST BUILD_TARGET BUILD_VENDOR BUILD_OPTIMIZE BUILD_LIB_OPTIMIZE BUILD_COMPILER BUILD_BOTH LIB_MACHINE_TYPE LIB_BUILD_TARGET LIB_BUILD_ABI LIB_BUILD_ARCH LIB_BUILD_HOST LIB2_MACHINE_TYPE LIB2_BUILD_TARGET LIB2_BUILD_ABI LIB2_BUILD_ARCH LIB2_BUILD_HOST BUILD_MULTILIB COMPILER_TARG_DIR TARG_INFO_NAME BUILD_TYPE GASNET_HOME ARMCI_HOME ARMCI_NETWORK_LIBS GASNET_CONDUITS DEFAULT_COMM UHCAF_MPI_INCLUDE UHCAF_MPI_FCFLAGS UHCAF_MPI_LDFLAGS CAFRT_ENABLE_DTRACES CAFRT_ENABLE_PROFILES DEFAULT_CAF_HEAP_SIZE DEFAULT_CAF_TEAMS_HEAP_SIZE EPIK_ROOT OPENUH_VERSION LIBLIST LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os BASH_PATH MPICC_PATH MACHINE_TYPE BUILD_ABI BUILD_ARCH BUILD_HOST BUILD_TARGET BUILD_VENDOR BUILD_OPTIMIZE BUILD_LIB_OPTIMIZE BUILD_COMPILER BUILD_BOTH LIB_MACHINE_TYPE LIB_BUILD_TARGET LIB_BUILD_ABI LIB_BUILD_ARCH LIB_BUILD_HOST LIB2_MACHINE_TYPE LIB2_BUILD_TARGET LIB2_BUILD_ABI LIB2_BUILD_ARCH LIB2_BUILD_HOST BUILD_MULTILIB COMPILER_TARG_DIR TARG_INFO_NAME BUILD_TYPE GASNET_HOME ARMCI_HOME ARMCI_NETWORK_LIBS GASNET_CONDUITS SHMEM_HOME SHMEM_LDFLAGS DEFAULT_COMM UHCAF_MPI_INCLUDE UHCAF_MPI_FCFLAGS UHCAF_MPI_LDFLAGS CAFRT_ENABLE_DTRACES CAFRT_ENABLE_PROFILES DEFAULT_CAF_HEAP_SIZE DEFAULT_CAF_TEAMS_HEAP_SIZE EPIK_ROOT OPENUH_VERSION LIBLIST LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -804,6 +804,10 @@ Optional Packages:
   --with-armci-network-libs=<armci libs>
                           Specify additional network libraries for linker when
                           using ARMCI
+  --with-shmem-root=<shmem path>
+                          Builds SHMEM-based libcaf runtime
+  --with-shmem-ldflags=<linker flags>
+                          Specify additional flags for linker when using SHMEM
   --with-default-comm=gasnet|armci
                           Default communication layer to use if GASNet and
                           ARMCI are supported. Will be GASNet if unspecified.
@@ -1434,6 +1438,26 @@ else
   ARMCI_NETWORK_LIBS=""
 fi;
 
+# enable SHMEM for Coarrays
+
+# Check whether --with-shmem-root or --without-shmem-root was given.
+if test "${with_shmem_root+set}" = set; then
+  withval="$with_shmem_root"
+  SHMEM_HOME="$with_shmem_root"
+else
+  SHMEM_HOME=""
+fi;
+
+# specify SHMEM linker flags
+
+# Check whether --with-shmem-ldflags or --without-shmem-ldflags was given.
+if test "${with_shmem_ldflags+set}" = set; then
+  withval="$with_shmem_ldflags"
+  SHMEM_LDFLAGS="$with_shmem_ldflags"
+else
+  SHMEM_LDFLAGS=""
+fi;
+
 # default comm library
 
 # Check whether --with-default-comm or --without-default-comm was given.
@@ -1553,9 +1577,9 @@ echo "$as_me: error: Could not find bash on system" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-if test -z "${GASNET_HOME}" -a -z "${ARMCI_HOME}"; then
-    { { echo "$as_me:$LINENO: error: Either --with-gasnet-root=<path> or --with-armci-root=<path> must be passed for coarrays" >&5
-echo "$as_me: error: Either --with-gasnet-root=<path> or --with-armci-root=<path> must be passed for coarrays" >&2;}
+if test -z "${GASNET_HOME}" -a -z "${ARMCI_HOME}" -a -z "${SHMEM_HOME}"; then
+    { { echo "$as_me:$LINENO: error: Either --with-gasnet-root=<path> or --with-armci-root=<path> or --with-shmem-root=<path> must be passed for coarrays" >&5
+echo "$as_me: error: Either --with-gasnet-root=<path> or --with-armci-root=<path> or --with-shmem-root=<path> must be passed for coarrays" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -1634,10 +1658,26 @@ echo "$as_me: error: Specified --with-gasnet-root=<path> does not look right. Ch
    fi
 fi
 
+if test -n "${SHMEM_HOME}"; then
+    if test ! -d "${SHMEM_HOME}"; then
+        { { echo "$as_me:$LINENO: error: Specified --with-shmem-root=<path> does not look right.  Check path." >&5
+echo "$as_me: error: Specified --with-shmem-root=<path> does not look right.  Check path." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+fi
+
+if test -n "${SHMEM_LDFLAGS}" -a -z "${SHMEM_HOME}"; then
+    { { echo "$as_me:$LINENO: error: --with-shmem-root=<path> must be specified if you want to use SHMEM" >&5
+echo "$as_me: error: --with-shmem-root=<path> must be specified if you want to use SHMEM" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 if test -z "${DEFAULT_COMM}" -a -n "${GASNET_HOME}"; then
   DEFAULT_COMM=gasnet
 elif test -z "${DEFAULT_COMM}" -a -n "${ARMCI_HOME}" ; then
   DEFAULT_COMM=armci
+elif test -z "${DEFAULT_COMM}" -a -n "${SHMEM_HOME}" ; then
+  DEFAULT_COMM=shmem
 elif test -n "${DEFAULT_COMM}" -a "${DEFAULT_COMM}" != "gasnet"  -a "${DEFAULT_COMM}" != "armci" ; then
     { { echo "$as_me:$LINENO: error: --with-default-comm accepts gasnet or armci" >&5
 echo "$as_me: error: --with-default-comm accepts gasnet or armci" >&2;}
@@ -1649,6 +1689,10 @@ echo "$as_me: error: default comm (gasnet) requires --with-gasnet-root to be spe
 elif test "${DEFAULT_COMM}" = "armci" -a -z "${ARMCI_HOME}" ; then
     { { echo "$as_me:$LINENO: error: default comm (armci) requires --with-armci-root to be specified" >&5
 echo "$as_me: error: default comm (armci) requires --with-armci-root to be specified" >&2;}
+   { (exit 1); exit 1; }; }
+elif test "${DEFAULT_COMM}" = "shmem" -a -z "${SHMEM_HOME}" ; then
+    { { echo "$as_me:$LINENO: error: default comm (shmem) requires --with-shmem-root to be specified" >&5
+echo "$as_me: error: default comm (shmem) requires --with-shmem-root to be specified" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -1980,6 +2024,8 @@ export GCC_CONFIGURE_CFLAGS
 
 
 
+
+
 # List of configurable files to create in object directory.
                     ac_config_files="$ac_config_files Makefile osprey/Makefile.gsetup"
 
@@ -2002,7 +2048,7 @@ fi
           ac_config_files="$ac_config_files osprey/targdir_lib/Makefile"
 
 
-                    ac_config_files="$ac_config_files osprey/targdir_lib/libcaf/Makefile osprey/targdir_lib/libcaf/armci/Makefile"
+                              ac_config_files="$ac_config_files osprey/targdir_lib/libcaf/Makefile osprey/targdir_lib/libcaf/armci/Makefile osprey/targdir_lib/libcaf/shmem/Makefile"
 
  if test -n "${GASNET_CONDUITS}"; then
    for conduit in $GASNET_CONDUITS; do
@@ -2023,7 +2069,7 @@ fi
 if test $BUILD_MULTILIB = "YES"; then
             ac_config_files="$ac_config_files osprey/targdir_lib2/Makefile:osprey/targdir_lib/Makefile.in"
 
-                        ac_config_files="$ac_config_files osprey/targdir_lib2/libcaf/Makefile:osprey/targdir_lib/libcaf/Makefile.in osprey/targdir_lib2/libcaf/armci/Makefile:osprey/targdir_lib/libcaf/armci/Makefile.in"
+                                  ac_config_files="$ac_config_files osprey/targdir_lib2/libcaf/Makefile:osprey/targdir_lib/libcaf/Makefile.in osprey/targdir_lib2/libcaf/armci/Makefile:osprey/targdir_lib/libcaf/armci/Makefile.in osprey/targdir_lib2/libcaf/shmem/Makefile:osprey/targdir_lib/libcaf/shmem/Makefile.in"
 
   if test -n "${GASNET_CONDUITS}"; then
     for conduit in $GASNET_CONDUITS; do
@@ -2595,12 +2641,14 @@ do
   "osprey/targdir_lib/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/Makefile" ;;
   "osprey/targdir_lib/libcaf/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libcaf/Makefile" ;;
   "osprey/targdir_lib/libcaf/armci/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libcaf/armci/Makefile" ;;
+  "osprey/targdir_lib/libcaf/shmem/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libcaf/shmem/Makefile" ;;
   "osprey/targdir_lib/libcaf/gasnet-${conduit}/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libcaf/gasnet-${conduit}/Makefile:osprey/targdir_lib/libcaf/gasnet/Makefile.in" ;;
   "osprey/targdir_lib/libcaf/gasnet/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libcaf/gasnet/Makefile" ;;
   "osprey/targdir_lib/init/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/init/Makefile:osprey/targdir_lib/init/Makefile.in" ;;
   "osprey/targdir_lib2/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/Makefile:osprey/targdir_lib/Makefile.in" ;;
   "osprey/targdir_lib2/libcaf/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libcaf/Makefile:osprey/targdir_lib/libcaf/Makefile.in" ;;
   "osprey/targdir_lib2/libcaf/armci/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libcaf/armci/Makefile:osprey/targdir_lib/libcaf/armci/Makefile.in" ;;
+  "osprey/targdir_lib2/libcaf/shmem/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libcaf/shmem/Makefile:osprey/targdir_lib/libcaf/shmem/Makefile.in" ;;
   "osprey/targdir_lib2/libcaf/gasnet-${conduit}/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libcaf/gasnet-${conduit}/Makefile:osprey/targdir_lib/libcaf/gasnet/Makefile.in" ;;
   "osprey/targdir_lib2/libcaf/gasnet/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libcaf/gasnet/Makefile:osprey/targdir_lib/libcaf/gasnet/Makefile.in" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -2728,6 +2776,8 @@ s,@GASNET_HOME@,$GASNET_HOME,;t t
 s,@ARMCI_HOME@,$ARMCI_HOME,;t t
 s,@ARMCI_NETWORK_LIBS@,$ARMCI_NETWORK_LIBS,;t t
 s,@GASNET_CONDUITS@,$GASNET_CONDUITS,;t t
+s,@SHMEM_HOME@,$SHMEM_HOME,;t t
+s,@SHMEM_LDFLAGS@,$SHMEM_LDFLAGS,;t t
 s,@DEFAULT_COMM@,$DEFAULT_COMM,;t t
 s,@UHCAF_MPI_INCLUDE@,$UHCAF_MPI_INCLUDE,;t t
 s,@UHCAF_MPI_FCFLAGS@,$UHCAF_MPI_FCFLAGS,;t t
@@ -3055,6 +3105,10 @@ echo "$as_me:    GASNET_CONDUITS                = $GASNET_CONDUITS" >&6;}
 echo "$as_me:    ARMCI_HOME                     = $ARMCI_HOME" >&6;}
 { echo "$as_me:$LINENO:    ARMCI_NETWORK_LIBS             = $ARMCI_NETWORK_LIBS" >&5
 echo "$as_me:    ARMCI_NETWORK_LIBS             = $ARMCI_NETWORK_LIBS" >&6;}
+{ echo "$as_me:$LINENO:    SHMEM_HOME                     = $SHMEM_HOME" >&5
+echo "$as_me:    SHMEM_HOME                     = $SHMEM_HOME" >&6;}
+{ echo "$as_me:$LINENO:    SHMEM_LDFLAGS                  = $SHMEM_LDFLAGS" >&5
+echo "$as_me:    SHMEM_LDFLAGS                  = $SHMEM_LDFLAGS" >&6;}
 { echo "$as_me:$LINENO:    UHCAF_MPI_INCLUDE              = $UHCAF_MPI_INCLUDE" >&5
 echo "$as_me:    UHCAF_MPI_INCLUDE              = $UHCAF_MPI_INCLUDE" >&6;}
 { echo "$as_me:$LINENO:    UHCAF_MPI_FCFLAGS              = $UHCAF_MPI_FCFLAGS" >&5
